### ISSUE TITLE
Error activating htseq-clip.simg

### ISSUE THREAD

**Issue by IrisWEI-1996** [EMBL-Hentze-group/htseq-clip#2]
Hi,

thanks for the useful tool! I met a problem when running the code which is the activation the .simg file. (/vol/hpctest not available)

----

The error info is as below:
Activating singularity image /home/global/tools/htseq-clip/htseq-clip.simg
WARNING: skipping mount of /vol/hpctest: no such file or directory
Error in rule do_extract_sites:
(check log file(s) for error message)

----

When trying 'singularity test htseq-clip.simg', I got the same error
WARNING: skipping mount of /vol/hpctest: no such file or directory

Since I'm using an HPC server, I don't have an administrator right and cannot visit, do you have any suggestions on how to modify or rebuild the .simg file? Or is there any other suggestion that I can run this tool?

Sincerely thank you,
Iris

**Comment by sudeepsahadevan** [comment]
Hi Iris,

Thanks for testing out htseq-clip. Is this the singularity image that is available from Hentze group webserver ? If yes, then this image might be a very old version which we do not actively maintain. I would encourage you to install the latest version from pip directly. What we would recommend is to install [conda](https://docs.anaconda.com/anaconda/install/index.html), create a separate environment for htseq-clip and install the latest version from pip.

Hope this helps,
Sudeep
