### ISSUE TITLE
OSError: [Errno 28] No space left on device while running htseq-clip count

### ISSUE THREAD

**Issue by connorrogerson** [EMBL-Hentze-group/htseq-clip#3]
I'm working through the worked example from https://link.springer.com/protocol/10.1007%2F978-1-0716-1851-6_10 but I'm stuck at counting crosslinks due to an error.

Command:
`htseq-clip count -i ../extract_xlink/1_xlink.bed -a /rds/user/cjr78/hpc-work/iCLIP/htseq-clip/annotation/SLBP_gencode_w50s20.txt -o 1_counts.csv`

The job fails and the output is:
[INFO]  run started at 2021-12-07 14:25 
[INFO]  Count crosslink sites
[INFO]  Annotation file /rds/user/cjr78/hpc-work/iCLIP/htseq-clip/annotation/SLBP_gencode_w50s20.txt crosslink sites file ../extract_xlink/1_trimmed.bam.csv
 [DEBUG]  {} format: sliding window annotation file
Traceback (most recent call last):
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/site-packages/clip/clip.py", line 245, in main
    _count(args)
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/site-packages/clip/clip.py", line 102, in _count
    countC.count(stranded)
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/site-packages/clip/countCLIP.py", line 228, in count
    with TempBed(self.annotation) as ta:
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/site-packages/clip/countCLIP.py", line 27, in __enter__
    copyfile(self.bedfile,self.tmpBed)
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
  File "/home/cjr78/miniconda3/envs/seq/lib/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
OSError: [Errno 28] No space left on device

A quick check of df -h shows plenty of space so I'm a bit lost. Any help will be appreciated!

**Comment by sudeepsahadevan** [comment]
Hi Connor, 
Thanks for the bug report. This could be because your `/tmp` is full. During `count` step, the annotation file is copied to the `/tmp` folder temporarily and then deleted. This was a hack work-around to get rid of the un-explainable crashes while running htseq-clip on an HPC with Slurm and snakemake.

**Comment by connorrogerson** [comment]
Hi Sudeep,

Thanks for getting back to me. That might make sense...Is there a way to specify a folder to copy the temp files to?

**Comment by sudeepsahadevan** [comment]
I'm afraid not at the moment. But, if it's ok for you to wait a couple of days, I'm happy to release a patched up version for this.

**Comment by sudeepsahadevan** [comment]
commit [d9600bf](https://github.com/EMBL-Hentze-group/htseq-clip/commit/ed8c2df34444b9f355452b80926a8e5cbf3c48b3) allows user to choose whether or not to copy files and the temp. folder to use. Updated version [2.10.0b0](https://pypi.org/project/htseq-clip/2.10.0b0/)

**Comment by connorrogerson** [comment]
If you write this in your bash script to submit to scheduler, this solves the issue.

`mkdir /rds/user/tmp_${SLURM_ARRAY_TASK_ID}`
`export TMPDIR=/rds/user/tmp_${SLURM_ARRAY_TASK_ID}`
`<script here>`
`rm -r /rds/user/tmp_${SLURM_ARRAY_TASK_ID}`
