### ISSUE TITLE
Not working on MacOSX

### ISSUE THREAD

**Issue by jenc42** [EMBL-Hentze-group/htseq-clip#5]
When running some commands e.g.
```
htseq-clip annotation -g gencode.v27.annotation.gff3 -o gencode.v27.annotation.bed
htseq-clip createSlidingWindows -i gencode.v27.annotation.bed -w 50 -s 20 -o SLBP_K562_w50s20.txt
```
The terminal comes out with the following error:
```
ImportError: cannot import name 'sched_getaffinity' from 'os' (/PATH/opt/anaconda3/envs/htseq-clip/lib/python3.7/os.py)
```
On inspection, 'os.py' is a file and 'os' as a folder within python3.7 does not exist. Online it has become clear that 'sched_getaffinity' is not a supported function on MacOSX and is available on Linux only. It appears therefore that MacOSX users are unable to run this code. 

Please may someone correct me if I am wrong (I am not an expert at Python), or recommend what can be done to edit this code for Mac users? Thank you.

**Comment by sudeepsahadevan** [comment]
Hi, 
Many thanks for reporting this. Could you please post the entire error stack trace ?

**Comment by jenc42** [comment]
Sure. For 
```
htseq-clip createSlidingWindows -i gencode.v27.annotation.bed -w 50 -s 20 -o SLBP_K562_w50s20.txt
```

the error stack trace is:
```
Traceback (most recent call last):
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/bin/htseq-clip", line 5, in <module>
    from clip.command_line import main
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/command_line.py", line 1, in <module>
    from . import clip
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/clip.py", line 10, in <module>
    from .bamCLIP import bamCLIP
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/bamCLIP.py", line 10, in <module>
    from os import sched_getaffinity
ImportError: cannot import name 'sched_getaffinity' from 'os' (/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/os.py)
```

Here is a screenshot to show there is no such directory or folder
<img width="680" alt="Screenshot 2022-03-23 at 08 05 03" src="https://user-images.githubusercontent.com/102179079/159651952-70480d57-f462-44ef-a2a5-8b06fde3924a.png">

Also the earlier command
```
htseq-clip annotation -g gencode.v27.annotation.gff3 -o gencode.v27.annotation.bed
```
comes up with error
```
Traceback (most recent call last):
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/bin/htseq-clip", line 5, in <module>
    from clip.command_line import main
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/command_line.py", line 1, in <module>
    from . import clip
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/clip.py", line 10, in <module>
    from .bamCLIP import bamCLIP
  File "/Users/Jen/opt/anaconda3/envs/htseq-clip/lib/python3.7/site-packages/clip/bamCLIP.py", line 10, in <module>
    from os import sched_getaffinity
ImportError: cannot import name 'sched_getaffinity' from 'os' (/Users/colema02/opt/anaconda3/envs/htseq-clip/lib/python3.7/os.py)
```

I got around this step by using an additional package to convert from BAM to BED however I don't know the contents of 'sliding windows' and i assume as this is to do with CPU it would need to be changed for most of the commands in Mac.

Thank you!

**Comment by sudeepsahadevan** [comment]
Thanks for your help. We will release a fix version as soon as possible

**Comment by jenc42** [comment]
thank you!

**Comment by sudeepsahadevan** [comment]
Thank you once again for reporting this issue
We've released a new version that will get rid of this issue on Mac
[`pip install htseq-clip==2.12.0b0`](https://pypi.org/project/htseq-clip/#description)

**Comment by jenc42** [comment]
thank you so much! this has fixed the issue.
