### ISSUE TITLE
Empty counts file 

### ISSUE THREAD

**Issue by Shashankti** [EMBL-Hentze-group/htseq-clip#7]
I followed the steps mentioned [here](https://link.springer.com/protocol/10.1007/978-1-0716-1851-6_10) to generate the counts file from my input bam file, however the counts file generated in completely empty.

Here is the sample code which I used:
```
htseq-clip annotation -g gencode.v21.annotation.gff3 -o gencode.v21.annotation.bed 
htseq-clip createSlidingWindows -i gencode.v21.annotation.bed -w 100 -s 20 v21_w100s20.txt
htseq-clip extract -i Merged_Gal_dedup.bam -e 1 -s e --primary -o Gal_R2_sites.bed
htseq-clip count -i Gal_R2_sites.bed -a v21_w100s20.txt
```

The output file generated is completely empty with just column names present. I tried to tweak some parameters in `createSlidingWindows` and used window sizes 25,50,100,300 and I also tried different parameters in the `extract` step, however I still get am empty file as an output.

Can you please help me in determining the right parameters for my use case? Thanks

**Comment by sudeepsahadevan** [comment]
Hi Shashankti,

Thanks for reporting this issue. Could you please check your `Gal_R2_sites.bed`  and see if its also empty ?

Thanks

**Comment by Shashankti** [comment]
Hi, thanks for the quick reply. The bed files are not empty, they look something like this:
```
1       15607   15608   NB501758:412:H32F3BGXB:4:13603:3683:18820_TGGGCCGCCACCACCCCCCCCC|49     1       +
1       15607   15608   NB501758:412:H32F3BGXB:3:12502:2678:5133_TGGGCCGCCACCACGACCCCCC|50      1       +
1       30253   30254   NB501758:412:H32F3BGXB:3:21410:23568:7968_TGCCGGAGGCAAACTTAAATAT|61     1       +
1       91393   91394   NB501758:412:H32F3BGXB:4:23609:22965:17977_TGCTGACCTCTGACGAGACTGA|48    1       +
1       91453   91454   NB501758:412:H32F3BGXB:1:12107:10982:5346_TAGCTGCCCCCAAGCAACGCAA|59     1       +
1       126899  126900  NB501758:412:H32F3BGXB:3:12409:18717:3698_GTACCCCGAGAAGGACCACACC|59     1       +
1       181603  181604  NB501758:412:H32F3BGXB:4:11511:2139:7908_AAGCACCTATATGTCTCTCCGT|60      1       -
1       182206  182207  NB501758:412:H32F3BGXB:1:21110:25112:5430_GAGACCGGCTTTTCCTCCGCCC|62     1       -
1       182206  182207  NB501758:412:H32F3BGXB:1:12310:14464:13736_GAGACCGGCTTTTGCATTTTAT|62    1       -

```

**Comment by Distue** [comment]
Thanks for checking. Can you please send the first 3000 lines (head -n
3000) of this file and the gff3 to biohentze at embl.de - we will have a
look.

Tom


Shashankti ***@***.***> schrieb am Mi., 30. Nov. 2022, 15:30:

**Comment by Shashankti** [comment]
Dear Tom,

Thank you for your response, I have sent the files on the email. Please let me know if you need any further information.

Shashank

**Comment by hentzelab** [comment]
Dear Shashank,
unfortunately, we have not received anything so far. 
Please be so kind to try again: 
***@***.***

Thank you.
Tom
On Thu, Dec 1, 2022 at 11:07, Shashankti  wrote: 
 Dear Tom,
 Thank you for your response, I have sent the files on the email. Please let me know if you need any further information.
 Shashank

**Comment by Shashankti** [comment]
Dear Tom,

I have sent the files again, please note that I am using my institute id instead of my personal gmail account to send the files. My email id is shashank.tiwari at mpi-dortmund.mpg.de
